### ISSUE TITLE
Support pydantic and fastapi

### ISSUE THREAD

**Issue by finswimmer** [snok/flake8-type-checking#52]
Hello,

`pydantic` and `fastapi` make use of typehints during runtime. Because `flake8-type-checking` doesn't know this, it leads to false recommendations to move typehints into the type-checking block.

## Example pydantic:

**model.py**
```
from typing import Optional

from pydantic import BaseModel

from pydantic import EmailStr


class Payload(BaseModel):
    id: Optional[int]
    text: str
    email: EmailStr
``` 

```
flake8 model.py
model.py:5:1: TC002 Move third-party import 'pydantic.EmailStr' into a type-checking block
```

Moving the import to the type-checking block and quote the usages leads to this error when pydantic tries to initialize an object:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "pydantic/main.py", line 404, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1040, in pydantic.main.validate_model
  File "pydantic/fields.py", line 699, in pydantic.fields.ModelField.validate
pydantic.errors.ConfigError: field "email" not yet prepared so type is still a ForwardRef, you might need to call Payload.update_forward_refs().
``` 

## Example fastapi

`api.py`:
```
import uvicorn
from fastapi import FastAPI

from model import Payload

app = FastAPI()


@app.post("/my_endpoint")
async def get_endpoint(payload: Payload):
    return None


if __name__ == "__main__":
    uvicorn.run(app)
```

```
flake8 api.py
api.py:4:1: TC002 Move third-party import 'model.Payload' into a type-checking block
```

Moving the import to the type-checking block and quote the usages leads to this error when when running the api:

```
Traceback (most recent call last):
  File "/home/finswimmer/tmp/minimal-fastapi/minimal_fastapi/example_api.py", line 13, in <module>
    async def get_endpoint(payload: "Payload"):
  File "/home/finswimmer/tmp/minimal-fastapi/.venv/lib/python3.8/site-packages/fastapi/routing.py", line 582, in decorator
    self.add_api_route(
  File "/home/finswimmer/tmp/minimal-fastapi/.venv/lib/python3.8/site-packages/fastapi/routing.py", line 525, in add_api_route
    route = route_class(
  File "/home/finswimmer/tmp/minimal-fastapi/.venv/lib/python3.8/site-packages/fastapi/routing.py", line 407, in __init__
    self.dependant = get_dependant(path=self.path_format, call=self.endpoint)
  File "/home/finswimmer/tmp/minimal-fastapi/.venv/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 278, in get_dependant
    endpoint_signature = get_typed_signature(call)
  File "/home/finswimmer/tmp/minimal-fastapi/.venv/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 248, in get_typed_signature
    typed_params = [
  File "/home/finswimmer/tmp/minimal-fastapi/.venv/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 253, in <listcomp>
    annotation=get_typed_annotation(param, globalns),
  File "/home/finswimmer/tmp/minimal-fastapi/.venv/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 265, in get_typed_annotation
    annotation = evaluate_forwardref(annotation, globalns, globalns)
  File "pydantic/typing.py", line 62, in pydantic.typing.evaluate_forwardref
    'MutableSet',
  File "/usr/lib/python3.8/typing.py", line 518, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Payload' is not defined
```

Any chance to handle this at least for `pydantic` and `fastapi` out of the box, as they are widely-used? (I've no idea if there would be a generic way). Of course using `# noqa` is always an option, but depending on the size of the application this might be a lot of work.

Thanks a lot for this super useful plugin :+1: 

fin swimmer

**Comment by sondrelg** [comment]
I've thought a little bit about this, since it's something I'd love to get to work - I use FastAPI and pydantic a fair bit myself. Right now, I would consider the plugin completely incompatible with any library or code that evaluates annotations outside the file they're declared in.

Thinking about the issue, I keep getting stuck at the problem of knowing when an annotation evaluated outside the file scope. Flake8-plugins are (softly/by-design) constrained to evaluating the source code of an individual file at the time, and we have to do so statically. Within those constraints I don't *think* it's possible to know if an annotation will be used by other code outside that scope.

I don't think that's possible, **but**, I suppose it might be possible to implement some simpler rules, like we could:
- prevent TC001/TC002 errors when annotations belong to a `BaseModel`-derived class declarations, and
- we might be able to make sense of which functions are wrapped by `@app.<method>` 

As an example, with the FastAPI example code you provided we *can* extract some info about the decorator:
```python
import ast
import textwrap

content = ast.parse(
    textwrap.dedent('''
    import uvicorn
    from fastapi import FastAPI
    
    from model import Payload
    
    app = FastAPI()
    
    
    @app.post("/my_endpoint")
    async def get_endpoint(payload: Payload):
        return None
    
    
    if __name__ == "__main__":
        uvicorn.run(app)
    ''')
)

functiondef = content[4]
print(functiondef.decorator_list[0].func.value.id)  # --> app
print(functiondef.decorator_list[0].func.attr)  # --> post
```

------------------------------------

If we assume we've already solved the Pydantic model issue completely, I'm left with two questions:

1. What are the places FastAPI evaluate annotations? Do we only need to care about endpoint declarations and pydantic models?

2. Assuming endpoints are all we need to worry about, what do you think about adding a setting/input for protected decorator patterns? It wouldn't be FastAPI specific, but might fix the FastAPI case by specifying, e.g., `type-checking-protected-decorator-patterns: ['\@\w+.(get|put|post|delete|patch|options|trace)\(']` 

That probably isn't a valid regex pattern, but let's pretend it matches `@app.<method>(` 😛

**Comment by finswimmer** [comment]
Hey @sondrelg,

I had similar solutions in my mind :) The more I thing about it, the less I'm convinced there is a solution that always works (Maybe it's because of my little knowledge about ast parsing ;)).

Providing a list of class names, where type hints for properties should be handled as "needed during runtime" sounds like a good idea. I guess it has its limitation as soon as a class inherits from another outside the current file. I guess this is something we have to live with.

I like the idea with the decorator-patterns :+1: I guess it will work in the most (maybe all?) cases.

> What are the places FastAPI evaluate annotations? Do we only need to care about endpoint declarations and pydantic models?

AFAIK yes.

fin swimmer

**Comment by sondrelg** [comment]
Perhaps just having a setting where the plugin never returns errors for annotations used in *any* class declarations would work for the pydantic case. Letting some false negatives through seems way better than risking some small % of false positives, since false positives will crash your app. 

As far as I can tell, we will need more than simple ast-parsing to do anything more fancy than that:

```python
import ast
import textwrap

content = (
    textwrap.dedent('''
    from pydantic import BaseModel
    
    class FirstModel(BaseModel):
        will_this_work: bool = True
        
    class SecondModel(MyModel):
        will_this_work: bool = False
    ''')
)

c = ast.parse(content)

print(c.body[1].bases[0].id)  # -> "BaseModel"
print(c.body[2].bases[0].id)  # -> "FirstModel"
```

Will look at this more when I get time 🙂

**Comment by sondrelg** [comment]
I hope to implement some support for Pydantic this week. This is how I see the issue currently. Please let me know if you see any flaws in the logic/suggested implementation.

### Fundamental problem

flake8-type-checking is set up to flag when an import can be moved out of the runtime scope of an application. It assumes that a resource that is only used for type hinting is **not required during the runtime of the application** - at all. 

This assumption is broken for Pydantic classes, since Pydantic evaluates annotations during runtime.

### Motivation

It would be nice if the flake8-hook could just ignore Pydantic code, so we can benefit from it elsewhere in an app. Specifically we want to avoid returning TC001/002-errors like this:

```python
from pydantic import condecimal, BaseModel  # TC002 Move third-party import 'pydantic.condecimal' into a type-checking block

from decimal import Decimal

class MyModel(BaseModel):
    total: condecimal(ge=Decimal(0)) = Decimal(0)
``` 

### Assumptions

- Since Pydantic models can inherit from other base models, any model with a base model could be a pydantic model.
- Classes without base models cannot be pydantic models
- Pydantic only evaluates annotations from class definitions
- Pydantic doesn't care about `from __futures__ import annotations` imports

### Implementation

I suggest we treat all annotations from class var definitions as "uses" of an import, when a pydantic setting is enabled.

We flag imports to be moved when there are *no uses*, so recording class annotations as uses should solve compatibility.

**Comment by sondrelg** [comment]
I just released [v1.2.0](https://github.com/snok/flake8-type-checking/releases/tag/v1.2.0) for Pydantic support. To enable it, just add this to your flake8 config: 

```ini
type-checking-pydantic-enabled = True
```

If you have a suitable project to test it on @finswimmer, that would be cool. I'll otherwise test it a bit more throughout the week 👍 

Was surprisingly easy to add in the end 🎉

**Comment by finswimmer** [comment]
Hey @sondrelg,

thanks a lot for your work :+1:

It works as expected in my projects. Treating all annotations from class var definitions as "uses" of an import seems to be the only possible solution in case of static code analysis, even with the downside that this leads to some false detection like in dataclasses.

So when will the fastapi support be released? :laughing: 

fin swimmer

**Comment by sondrelg** [comment]
I think we would just need to be certain about exactly what parts of FastAPI evaluates annotations to then be sure whether it's supportable or not. Input and/or PRs are welcome for anyone reading this 🙂 

For FastAPI support, would it be enough to, e.g., count all function definition type hints when they're decorated? 

@JonasKs I think you thought of one other thing to consider last time we discussed this; do you remember?

**Comment by JonasKs** [comment]
Hmmm, I remember the conversation, but not the conclusion. Let me think about it! 

Routes, decorators, kwargs..?

**Comment by sondrelg** [comment]
I think I'll have time to sit down and work on this the next few days, so here's my thoughts so far:

Looking at FastAPI, I think there are two main sources of annotation evaluation:

1. Routes
2. Dependencies

And there might be others that I've missed - if so, please let me know 👏 

### Routes

By routes i mean this general pattern

```python
from fastapi import APIRouter

some_router = APIRouter(prefix='/some-path')

@some_router.get('/')
async def list_something(some_model: SomeModel):
    ...
```

This pattern seems easy to recognize. We can treat annotations as "uses" when the type of the function definition is `AsyncFunctionDef`, and the length of decorators are > 0.

Quick control question: sync function views don't exist in FastAPI do they?

### Dependencies

This is where things get problematic, and where I need some help to land on a good design:

The fact that callables passed to `Depends` are evaluated  means that *any annotation* in *any function definition* can be evaluated.

If there was some way for flake8-plugins to maintain global, we *could* keep track of what functions were passed to `Depends` around a project, but to my knowledge we're constrained to handling a single file at the time. In other words, if flake8 had some hook to pass state between files that might be one way to handle this pretty well.

Assuming for a second that we *are* constrained to handling a single file at the time, I'm a little torn about how to proceed. As far as I can tell there are only two options:

#### Minimising false positives

If we wanted to optimise for no false positives, we would be forced to treat **all function argument annotations as uses**. 

Since the pydantic-support optio already treats all class annotations as uses, I'm not sure the plugin would have much value left. Function and class annotations seem like it would easily be 90%+ of an applications type hints, for most projects.

#### Maximising plugin value

Another option could be to make a decision *not* to handle dependencies. We could handle the route pattern, and inform users that they need to be wary of dependency false positives. 

This would mean the plugin would work normally for 99% of function definitions, but means we'd get consistent false positives for dependencies. Notably, false positives mean runtime errors for users, which is pretty far from ideal.

-----------------

What do you think?

**Comment by sondrelg** [comment]
I suppose even if there was something like global state, for a run, in flake8, mapping dependencies would still only work if:

- Flake8 scanned the entire project (not, e.g., a single file), or
- There was some sort of caching involved to make sure we had access to the state of previous runs

**Comment by sondrelg** [comment]
Just released [v1.3.0](https://github.com/snok/flake8-type-checking/releases) with `--type-checking-fastapi-enabled` added. Enabling the setting will change the behaviour of the plugin to count annotations from any decorated function definition as required at runtime.

You can enable it like this:

```ini
[flake8]
...
enable-extensions = TC, TC2  # or TC1
type-checking-fastapi-enabled = True
type-checking-exempt-modules = typing
```

Or by running flake8 like this:

```shell
flake8 . --type-checking-fastapi-enabled
```

Ended up not implementing "support" for `dependencies`, meaning there will be some unhandled false positives for normal functions that are passed to `Depends` calls. If anyone has any suggestions for how to improve this, I'm all ears 👏

**Comment by sondrelg** [comment]
I made a few small mistakes in v1.3.0, so looks like I'll yank 1.3.0 and release 1.3.1 with two additional features:

- FastAPI dependency support
- A setting for whitelisting base classes (to, e.g., not ignore type hints in a `NamedTuple` only because pydantic support is enabled)

**Comment by danpker** [comment]
What is the desired behaviour for return types with FastAPI? According to this test, `CustomType` should be moved to a `TYPE_CHECKING` block.

```
@pytest.mark.parametrize('fdef', ['def', 'async def'])
def test_api_router_decorated_function_return_type(fdef):
    """
    We don't care about return types. To my knowledge,
    these are not evaluated by FastAPI/pydantic.
    """
    example = textwrap.dedent(f'''
        from fastapi import APIRouter
        from fastapi import Request

        from app.types import CustomType

        some_router = APIRouter(prefix='/some-path')

        @some_router.get('/{{resource_id}}')
        {fdef} list_something(request: Request) -> CustomType:
            return None
        ''')
    assert _get_error(example, error_code_filter='TC001,TC002,TC003', **defaults) == {
        '5:0 ' + TC002.format(module='app.types.CustomType')
    }
```

However, doing so, even with a pretty basic route gives the following error in FastAPI:
```
     def test() -> Test:
                   ^^^^
 NameError: name 'Test' is not defined
```

**Comment by sondrelg** [comment]
Seems unexpected that this would be flagged this way, since there's no futures import 🤔 Would you mind opening a new issue for this @danpker?

**Comment by Daverball** [comment]
@danpker @sondrelg  It's possible that this this is an artifact of FastAPI making use of `typing.get_type_hints` which would require all the annotations on the function to be available at runtime, regardless of whether they're being used or not.

[PEP-649](https://peps.python.org/pep-0649/) + switching to `typing_extensions.get_type_hints` could potentially remedy this in the near future, but I also don't see much of a problem of guarding against this and adding the return annotation to the list of exclusions for the FastAPI plugin.

**Comment by danpker** [comment]
@sondrelg Raised as #185
