### ISSUE TITLE
Support attrs

### ISSUE THREAD

**Issue by sasanjac** [snok/flake8-type-checking#77]
Similar to #52, [`attrs`](https://github.com/python-attrs/attrs) makes use of type hints during runtime. `flake8-type-checking` however recommends moving these type hints into a type-checking block.

# Example
`example.py`
```
from attr import define

from models.grid import Grids


@define
class GridController:
    grids: Grids
```

`Move third-party import 'models.grid.Grids' into a type-checking block flake8(TC002)`

Moving the import into a type-checking block results in an error of course.

Maybe it's possible to generalize the approach taken for `pydantic` and `fastapi` and extend it to all dataclass-like patterns?

**Comment by sondrelg** [comment]
if there are predictable ways of knowing whether a class is an `attrs` class, then I think we can actually do a better job with `attrs` than with `pydantic`. When pydantic support is enabled we treat *all* class var annotations as needed, since we cannot be sure what classes are pydantic classes and not.

Do you know if `define` is the only decorator used when defining a class with type hints? I'm familiar with the library, but haven't used it extensively 👍

**Comment by sasanjac** [comment]
There is also `attr.s`:

```
import attr

from models.grid import Grids


@attr.s(auto_attribs=True)
class GridController:
    grids: Grids
```
